<?

if (!isset($_NS_TRACK_VARS)) $_NS_TRACK_VARS=array();
$_NS_TRACK_VARS['Skip']=false;
$_NS_TRACK_VARS['IpId']=0;
$_NS_TRACK_VARS['AgentId']=0;
$_NS_TRACK_VARS['Settings']=array();
$_NS_TRACK_VARS['CheckCookieId']=false;
$_NS_TRACK_VARS['HostsArr']=false;
$_NS_TRACK_VARS['Undef']=false;
$_NS_TRACK_VARS['LogId']=0;
$_NS_TRACK_VARS['CompanyId']=false;
$_NS_TRACK_VARS['Current']=false;
$_NS_TRACK_VARS['GetVars']=array();
$_NS_TRACK_VARS['PresetIP']=false;
$_NS_TRACK_VARS['PresetID']=false;
$_NS_TRACK_VARS['StId']=false;
$_NS_TRACK_VARS['NaturalKey']=0;
$_NS_TRACK_VARS['CookieLogSet']=false;
$_NS_TRACK_VARS['UpdateVisPath']=false;
$_NS_TRACK_VARS['SSL']=false;
$_NS_TRACK_VARS['RefHostId']=0;
$_NS_TRACK_VARS['SourceId']=0;
$_NS_TRACK_VARS['Item']=false;
$_NS_TRACK_VARS['PageId']=0;
$_NS_TRACK_VARS['RefSet']=0;
$_NS_TRACK_VARS['QueryId']=0;
$_NS_TRACK_VARS['VisId']=0;
$_NS_TRACK_VARS['TimeDblPageLoad']=0;
$_NS_TRACK_VARS['TimeDblAdvClick']=0;
$_NS_TRACK_VARS['TimeDblSale']=0;
$_NS_TRACK_VARS['TimeDblEvent']=0;
$_NS_TRACK_VARS['ClickSubId']=0;
$_NS_TRACK_VARS['KeyId']=0;
$_NS_TRACK_VARS['Actions']=array();
$_NS_TRACK_VARS['Fraud']=0;
$_NS_TRACK_VARS['SiteHostId']=0;
$_NS_TRACK_VARS['UpdateVisPath']=false;
$_NS_TRACK_VARS['Site']=false;
$_NS_TRACK_VARS['COOKIE_DOMAIN']=false;
$_NS_TRACK_VARS['FindLastNode']=true;

$_NS_TRACK_VARS['Cost']=false;
$_NS_TRACK_VARS['CustomId']=false;
$_NS_TRACK_VARS['AddInfo']=false;
$_NS_TRACK_VARS['Items']=array();

$_NS_TRACK_VARS['ScrRes']=false;
$_NS_TRACK_VARS['PxD']=false;
$_NS_TRACK_VARS['FlVer']=false;
$_NS_TRACK_VARS['Frame']=false;

$Skip=&$_NS_TRACK_VARS['Skip'];
$CompanyId=&$_NS_TRACK_VARS['CompanyId'];
$StId=&$_NS_TRACK_VARS['StId'];
$VisId=&$_NS_TRACK_VARS['VisId'];
$LogId=&$_NS_TRACK_VARS['LogId'];
$PageId=&$_NS_TRACK_VARS['PageId'];
$QueryId=&$_NS_TRACK_VARS['QueryId'];
$Current=&$_NS_TRACK_VARS['Current'];
$CookieLogSet=&$_NS_TRACK_VARS['CookieLogSet']; $IpId=$IpId=&$_NS_TRACK_VARS['IpId'];
$AgentId=&$_NS_TRACK_VARS['AgentId'];
$Settings=&$_NS_TRACK_VARS['Settings'];
$CheckCookieId=&$_NS_TRACK_VARS['CheckCookieId'];
$UpdateVisPath=&$_NS_TRACK_VARS['UpdateVisPath'];
$HostsArr=&$_NS_TRACK_VARS['HostsArr'];
$RefHostId=&$_NS_TRACK_VARS['RefHostId']; $SourceId=&$_NS_TRACK_VARS['SourceId'];  $KeyId=&$_NS_TRACK_VARS['KeyId'];  $RefSet=&$_NS_TRACK_VARS['RefSet'];
$NaturalKey=&$_NS_TRACK_VARS['NaturalKey'];
$SiteHostId=&$_NS_TRACK_VARS['SiteHostId']; $SSL=&$_NS_TRACK_VARS['SSL'];
$Site=&$_NS_TRACK_VARS['Site'];
$ClickSubId=&$_NS_TRACK_VARS['ClickSubId'];
$ScrRes=&$_NS_TRACK_VARS['ScrRes'];
$PxD=&$_NS_TRACK_VARS['PxD'];
$FlVer=&$_NS_TRACK_VARS['FlVer'];
$Frame=&$_NS_TRACK_VARS['Frame'];
$FindLastNode=&$_NS_TRACK_VARS['FindLastNode']; $PresetIP=&$_NS_TRACK_VARS['PresetIP'];
$PresetID=&$_NS_TRACK_VARS['PresetID'];
$PresetIP=NS_TRACK_MISC::ValidVar($_GP['presetIP']);
$PresetID=NS_TRACK_MISC::ValidVar($_GP['presetID']);

?>